eureka:
  client:
    serviceUrl:
      defaultZone: http://appfrg01.cpd.frago.net:18082/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
management:
  security:
    enabled: false    