server:
  port: 18080
spring:
  application:
    name: gateway
eureka:
  client:
    region: default
    registryFetchIntervalSeconds:  5
    serviceUrl:
      defaultZone: http://appfrg01.cpd.frago.net:18082/eureka    